### ISSUE TITLE
Create Page - Remove submit button blur

### ISSUE THREAD

**Issue by mpaiva** [MarcelloPaiva/nolatin#37]
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/781670/218266274-4654dae4-c438-4dc8-b72e-0f3f9597a9dc.png">

**Comment by mpaiva** [comment]
Based on our discussion, let's remove the "blur" behavior for now. We can revisit this in the future. Here's the use-case:

- if the user hits the "Add Page" button without filling the, read blank inputs:
  - Add the following default values to the input fields on submission 
  - Page Tile: "Rename this page"
  - Description: "Don't procrastinate, add a good description to this page, screen-reader users depend on you to have a better user experience."

Let me know if you are good with these changes.


<img width="613" alt="image" src="https://user-images.githubusercontent.com/781670/220663762-6cfe1655-1099-43ce-bb7a-453a918ee793.png">

**Comment by MarcelloPaiva** [comment]
done
