### ISSUE TITLE
Add a "description" field to "Heading" and "Heading Link" content cards

### ISSUE THREAD

**Issue by mpaiva** [MarcelloPaiva/nolatin#56]
The rationale is to provide a better usability for headings, by always attaching a paragraph next to a heading and attach the attribute `aria-describedby` to the heading.

This is something we are pushing as good content design practice. 

Example:
```
<h2 aria-describedby="h-desc-001">Job Search</h2>
…
<p id="h-desc-001">
 Search for jobs by title or location, if you are looking for a remote position, type "remote" in the location field.
</p>
```

<img width="537" alt="image" src="https://user-images.githubusercontent.com/781670/219877901-b36878b5-a810-4bb3-92ea-d7d60457b872.png">

**Comment by MarcelloPaiva** [comment]
done
