### ISSUE TITLE
Bulleted list of links need a "label" 

### ISSUE THREAD

**Issue by mpaiva** [MarcelloPaiva/nolatin#61]
It would be helpful to allow these bulleted links to have a label and a destination URL, like you did in the Heading link.

Perhaps, instead of `("url1" "url2")` you could do `("label, url1" "label, url2")`? 

<img width="408" alt="image" src="https://user-images.githubusercontent.com/781670/219902232-a7134e31-a933-458b-80ca-a79e307f8c92.png">

**Comment by MarcelloPaiva** [comment]
done
